//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacationRequest
    {
        public int RequestID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> VacationStart { get; set; }
        public Nullable<System.DateTime> VacationEnd { get; set; }
        public string VacationReason { get; set; }
        public string RequestStatus { get; set; }
        public string RequestDeletedReason { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
